# -*- mode: python ; coding: utf-8 -*-
# BenchFlow – Windows build spec
# Run:  python -m PyInstaller --noconfirm --distpath dist\windows BenchFlow_windows.spec

import os
from PyInstaller.utils.hooks import collect_all

datas    = []
binaries = []
hiddenimports = []

tmp_ret = collect_all('customtkinter')
datas    += tmp_ret[0]
binaries += tmp_ret[1]
hiddenimports += tmp_ret[2]

# Use AppIcon.ico if it exists (generated by build script / CI)
_icon = 'AppIcon.ico' if os.path.exists('AppIcon.ico') else None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'tensorflow', 'scipy', 'pandas', 'numpy', 'pyarrow',
        'matplotlib', 'PyQt5', 'IPython', 'jupyter', 'notebook',
        'dask', 'distributed', 'botocore', 'boto3', 'openpyxl',
        'h5py', 'zarr', 'xarray', 'statsmodels', 'numba', 'llvmlite',
        'sympy', 'sklearn',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BenchFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,               # windowed mode – no terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BenchFlow',
)
